# Generated by Django 4.1.1 on 2022-12-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webBookwormPL", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booklist", name="isbn", field=models.IntegerField(null=True),
        ),
    ]
